In [1]:
import gym
import numpy as np

In [2]:
env = gym.make('FrozenLake-v0')

[2017-10-23 16:07:28,307] Making new env: FrozenLake-v0


## Implementing Q-table learning algorithm

In [10]:
# initialize table with all zeros
Q = np.zeros([env.observation_space.n, env.action_space.n])

# Set learning parameters
lr = 0.8
y = 0.95
num_episodes = 200

# create lists to contain total rewards and steps per episode
rList=[]

for i in range(num_episodes):
    # rest environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    
    # The Q-Learning algorithm
    while j<99:
        j+=1
        a = np.argmax(Q[s, :] + np.random.randn(1, env.action_space.n) * (1./(i+1)))
        
        # Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)
    

In [11]:
print ("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.025


In [12]:
print ("Final Q-Table Values")
print (Q)

Final Q-Table Values
[[  5.45845565e-03   5.39043572e-03   5.56316202e-03   5.86486151e-03]
 [  9.71966760e-04   6.63813202e-03   2.06635796e-04   2.72997011e-01]
 [  7.48084258e-03   8.65659263e-02   7.22541972e-03   6.75905587e-03]
 [  5.88106851e-02   2.78684779e-05   1.32846183e-03   6.40843757e-03]
 [  1.12262653e-02   9.90203744e-04   1.33022454e-03   2.24855625e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  8.16341021e-03   2.88582073e-02   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.16050799e-03   1.10355701e-02   1.06237650e-03   1.02564711e-02]
 [  1.06488314e-02   6.50724943e-01   3.36653037e-04   0.00000000e+00]
 [  8.63338964e-03   0.00000000e+00   1.46646756e-01   1.25969263e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   5.56445991e-03   8.86654186e-03   0